shared:
    image: node:6

jobs:
    job1:
        steps:
          - echo: echo hi
        requires: [~commit, ~pr]
    job2:
        steps:
          - echo: sleep 10
        requires: [~commit, ~pr]
    job3:
        steps:
          - echo: sleep 20
        requires: [~commit, ~pr]
    bbJob2:
        steps:
          - echo: echo bye
        requires: job1
        blockedBy: job2
    bbJob23:
        steps:
            - echo: echo hello
        requires: job1
        blockedBy: [job2, job3]
    bbEx:
        steps:
          - echo: echo bye
        blockedBy: ~sd@526:job1
