shared:
    image: node:6

jobs:
    job1:
        steps:
          - sleep: sleep 10
        requires: [~commit, ~pr]
    job2:
        steps:
          - echo: echo i am blocked
        requires: [~commit, ~pr]
        blockedBy: job1
    job3:
        steps:
          - echo: echo bye
        requires: [~commit, ~pr]
        blockedBy: job1
    job4:
        steps:
          - echo: echo bye
        requires: [~commit, ~pr]
        blockedBy: sd@526:job1
