shared:
    image: node:6

jobs:
    job1:
        steps:
          - sleep: sleep 10
        requires: [~commit, ~pr]
    blockedByJob1:
        steps:
          - echo: echo i am blocked
        requires: [~commit, ~pr]
        blockedBy: job1
    notblocked:
        steps:
          - echo: echo bye
        requires: [~commit, ~pr]
        blockedBy: job1
    blockedByExternal:
        steps:
          - echo: echo bye
        requires: [~commit, ~pr]
        blockedBy: ~sd@526:job1
