shared:
    image: node:6

jobs:
    job1:
        steps:
          - sleep: sleep 10
        requires: [~commit, ~pr]
    job2:
        steps:
          - echo: sleep 30
        requires: [~commit, ~pr]
    blockedByJob1:
        steps:
          - echo: echo i am blocked
        requires: [~commit, ~pr]
        blockedBy: job1
    blockedByJob12:
        steps:
          - echo: echo i am blocked
        requires: [~commit, ~pr]
        blockedBy: 
            - job1
            - job2
    blockedByExternal:
        steps:
          - echo: echo bye
        requires: [~commit, ~pr]
        blockedBy: ~sd@526:job1
